### ISSUE TITLE
Data Explanation

### ISSUE THREAD

**Issue by omarsar** [huseinzol05/Malaya-Dataset#1]
Is it possible for you to explain how you obtained the datasets? I am very interested in using some of them for research purposes, but I couldn't find the explanation on how they were retrieved.

Great datasets by the way! :)

**Comment by huseinzol05** [comment]
crawl, augmentation using synonyms, POS searching by voting combination spacy and nltk.

**Comment by omarsar** [comment]
Thanks for your reply! 
I was interested in how you came up with the seeds and labels for the emotion dataset (6 labels).
Any help is appreciated! :+1:
