### ISSUE TITLE
Preprocessing Wikipedia dumps

### ISSUE THREAD

**Issue by AnakTeka** [huseinzol05/Malaya-Dataset#2]
How did you preprocess the dumps for Wikpedia for obtaining the sentences on .json file?

**Comment by huseinzol05** [comment]
I just realized after I saw your issue, gensim did preprocessing, which, remove punct, remove special letters during tokenization and make all small letters. I fixed and added new link for **RAW**, only split by space during tokenization, https://github.com/huseinzol05/Malaya-Dataset#multidomain
