### ISSUE TITLE
training time inquiry

### ISSUE THREAD

**Issue by LydiaXiaohongLi** [huseinzol05/Malaya-Dataset#3]
Hi huseinzol05,

Thanks for your github repo, really helpful. I am trying to pretrain albert-base-v2 on my own custom chatlogs (domain specific), I am training using 4 nvidia T4 GPU, model configuration same as albert-base, when i set batch size as 512, it takes around 20 mins for 1000 batches (i.e. steps), may I ask what is your training setup and training time for your albert/bert model pretrain? Thanks! 

Regards
Xiaohong

**Comment by huseinzol05** [comment]
albert, https://github.com/huseinzol05/Malaya/tree/master/pretrained-model/albert-brightmart

bert, https://github.com/huseinzol05/Malaya/tree/master/pretrained-model/bert

I never able to train albert v2 even on 4 Tesla 32GB VRAM.

**Comment by LydiaXiaohongLi** [comment]
Thanks! Noticed u were training on 3 V100 GPU, (with batch_size of 120 and 1mil steps), may i ask if you remember roughly how long it takes for your setup?

**Comment by huseinzol05** [comment]
4 steps per second, roughly 70 hours.

**Comment by LydiaXiaohongLi** [comment]
Thank you!
